export const Routes = {
  AUTH: 'auth',
  LOGIN: 'login',
  REGISTER: 'register',
  REFRESH: 'refresh',
  LOGOUT: 'logout',
  SESSIONS: 'sessions',
  MOVIES: 'movies',
  FILTERS: 'filters',
  FEATURED: 'featured',
  PRODUCTS: 'products',
  FAVORITES: 'favorites',
  USERS: 'users',
  ME: 'me',
  REVIEWS: 'reviews',
  ALL: 'all',
} as const;
